// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3

#ifndef _DHT8_3_UI_H
#define _DHT8_3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"
extern int desktopcnt;
void iconNOW2PRE_Animation(lv_obj_t * TargetObject, int vTaskDelay);
void iconNEX2NOW_Animation(lv_obj_t * TargetObject, int vTaskDelay);
void iconAppear_Animation(lv_obj_t * TargetObject, int vTaskDelay);
void icondisapp_Animation(lv_obj_t * TargetObject, int vTaskDelay);
void iconPRE2NOW_Animation(lv_obj_t * TargetObject, int vTaskDelay);
void iconNOW2NEX_Animation(lv_obj_t * TargetObject, int vTaskDelay);

// SCREEN: ui_DESK
void ui_DESK_screen_init(void);
extern lv_obj_t * ui_DESK;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_iconPRE2;
extern lv_obj_t * ui_iconNEX2;
extern lv_obj_t * ui_iconNEX;
extern lv_obj_t * ui_iconPRE;
extern lv_obj_t * ui_iconNOW;
extern lv_obj_t * ui_Container1;
void ui_event_ButtonDown(lv_event_t * e);
extern lv_obj_t * ui_ButtonDown;
void ui_event_ButtonUp(lv_event_t * e);
extern lv_obj_t * ui_ButtonUp;
void ui_event_ButtonCen(lv_event_t * e);
extern lv_obj_t * ui_ButtonCen;
extern lv_obj_t * ui_battery0;
extern lv_obj_t * ui_batvalue;
extern lv_obj_t * ui_battery1;
// CUSTOM VARIABLES

// SCREEN: ui_CLOCK
void ui_CLOCK_screen_init(void);
extern lv_obj_t * ui_CLOCK;
extern lv_obj_t * ui_Container3;
void ui_event_ButtonDown1(lv_event_t * e);
extern lv_obj_t * ui_ButtonDown1;
extern lv_obj_t * ui_ButtonUp1;
extern lv_obj_t * ui_ButtonCen1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_HOUR;
extern lv_obj_t * ui_MIN;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label3;
void ui_event_ButtonBACK(lv_event_t * e);
extern lv_obj_t * ui_ButtonBACK;
// CUSTOM VARIABLES

// SCREEN: ui_SETTING
extern int leddut;
extern int wifistatu;
void ui_event_BLslider(lv_event_t * e);
void ui_SETTING_screen_init(void);
extern lv_obj_t * ui_SETTING;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_BLslider;
void ui_event_ButtonBACK1(lv_event_t * e);
extern lv_obj_t * ui_ButtonBACK1;
extern lv_obj_t * ui_backtext;
extern lv_obj_t * ui_BLtext;
void ui_event_ButtonGETTIME(lv_event_t * e);
extern lv_obj_t * ui_ButtonGETTIME;
extern lv_obj_t * ui_GetTimetext;
extern lv_obj_t * ui_SETTINGtext;
void ui_event_SETTINGKEY(lv_event_t * e);
extern lv_obj_t * ui_SETTINGKEY;
extern lv_obj_t * ui_WIFItext;
void ui_event_WIFIKEY(lv_event_t * e);
extern lv_obj_t * ui_WIFIKEY;
// CUSTOM VARIABLES

// SCREEN: ui_CALENDAR
void ui_CALENDAR_screen_init(void);
void ui_event_ButtonBACK5(lv_event_t * e);
extern lv_obj_t * ui_CALENDAR;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_ButtonDown2;
extern lv_obj_t * ui_ButtonUp2;
extern lv_obj_t * ui_ButtonCen2;
extern lv_obj_t * ui_Calendar1;
void ui_event_ButtonDown2(lv_event_t * e);
void ui_event_ButtonUp2(lv_event_t * e);
void ui_event_ButtonCen2(lv_event_t *e);
extern lv_obj_t * ui_ButtonBACK5;
// CUSTOM VARIABLES

// SCREEN: ui_SETTIME
extern int timeset[4] ;
void ui_SETTIME_screen_init(void);
extern lv_obj_t * ui_SETTIME;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_ButtonDown4;
extern lv_obj_t * ui_ButtonUp4;
extern lv_obj_t * ui_ButtonCen4;
void ui_event_ButtonBACK2(lv_event_t * e);
extern lv_obj_t * ui_ButtonBACK2;
extern lv_obj_t * ui_backtext1;
void ui_event_getTWifiBtn(lv_event_t * e);
extern lv_obj_t * ui_getTWifiBtn;
extern lv_obj_t * ui_getTWifi;
void ui_event_timeSetBtn(lv_event_t * e);
extern lv_obj_t * ui_timeSetBtn;
extern lv_obj_t * ui_timeSet;
extern lv_obj_t * ui_Hour0;
extern lv_obj_t * ui_hour0label;
extern lv_obj_t * ui_Hour1;
extern lv_obj_t * ui_hour1label;
extern lv_obj_t * ui_Min0;
extern lv_obj_t * ui_min0label;
extern lv_obj_t * ui_Min1;
extern lv_obj_t * ui_min1label;
extern lv_obj_t * ui_settimeLabel1;
extern int hour1;
extern int min1;
extern int hour2;
extern int min2;
extern int hour3;
extern int min3;
extern int settimemod;
void ui_event_Hour0(lv_event_t * e);
void ui_event_Hour1(lv_event_t * e);
void ui_event_Min0(lv_event_t * e);
void ui_event_Min1(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_AiChat
void ui_AiChat_screen_init(void);
extern lv_obj_t * ui_AiChat;
extern lv_obj_t * ui_Container10;
void ui_event_ButtonBACK4(lv_event_t * e);
extern lv_obj_t * ui_ButtonBACK4;
extern lv_obj_t * ui_aichattext1;
extern lv_obj_t * ui_aichattext2;
extern lv_obj_t * ui_aichatSpinner1;
void ui_event_ChatBtn(lv_event_t * e);
extern lv_obj_t * ui_ChatBtn;
// CUSTOM VARIABLES


// SCREEN: ui_Aiassistant
void ui_Aiassistant_screen_init(void);
extern lv_obj_t * ui_Aiassistant;
extern lv_obj_t * ui_Container11;
//void ui_event_ButtonBACK3(lv_event_t * e);
extern int Ailocalmode;
extern lv_obj_t * ui_aiassistantSpinner1;
extern lv_obj_t * ui_aiassistantSpinner2;
void ui_event_aiassistantlabel2(lv_event_t * e);
extern lv_obj_t * ui_aiassistantlabel2;
void ui_event_aiassistantSwitch1(lv_event_t * e);
extern lv_obj_t * ui_aiassistantSwitch1;
extern lv_obj_t * ui_aiassistantlabel1;
void ui_event_ButtonBACK6(lv_event_t * e);
extern lv_obj_t * ui_ButtonBACK6;
extern lv_obj_t * ui_aiassistantSwitch1;
extern lv_obj_t * ui_aiassistantSwitchtext;
// CUSTOM VARIABLES

// SCREEN: ui_LIGHT
void ui_LIGHT_screen_init(void);
extern lv_obj_t * ui_LIGHT;
void ui_event_ButtonBACK7(lv_event_t * e);
extern lv_obj_t * ui_ButtonBACK7;
void ui_event_ButtonUp5(lv_event_t * e);
extern lv_obj_t * ui_ButtonUp5;
void ui_event_ButtonDown5(lv_event_t * e);
extern lv_obj_t * ui_ButtonDown5;
extern lv_obj_t * ui_Image1;

// SCREEN: ui_ALARM
void ui_ALARM_screen_init(void);
extern lv_obj_t * ui_ALARM;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Container15;
void ui_event_ButtonBACK9(lv_event_t * e);
extern lv_obj_t * ui_ButtonBACK9;
extern lv_obj_t * ui_backtext4;
extern lv_obj_t * ui_Alarm1;
void ui_event_Alarmkey(lv_event_t * e);
extern lv_obj_t * ui_Alarmkey;
void ui_event_Alarmbtn(lv_event_t * e);
extern lv_obj_t * ui_Alarmbtn;
extern lv_obj_t * ui_Alarmtext;
extern lv_obj_t * ui_Alarm2;
void ui_event_Alarmkey2(lv_event_t * e);
extern lv_obj_t * ui_Alarmkey2;
void ui_event_Alarmbtn2(lv_event_t * e);
extern lv_obj_t * ui_Alarmbtn2;
extern lv_obj_t * ui_Alarmtext2;
extern lv_obj_t * ui_Alarm3;
void ui_event_Alarmkey3(lv_event_t * e);
extern lv_obj_t * ui_Alarmkey3;
void ui_event_Alarmbtn3(lv_event_t * e);
extern lv_obj_t * ui_Alarmbtn3;
extern lv_obj_t * ui_Alarmtext3;



// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_icon4_png);    // assets/icon4.png
LV_IMG_DECLARE(ui_img_icon1_png);    // assets/icon1.png
LV_IMG_DECLARE(ui_img_icon3_png);    // assets/icon3.png
LV_IMG_DECLARE(ui_img_icon2_png);    // assets/icon2.png
LV_IMG_DECLARE(ui_img_icon5_png);    // assets/icon5.png
LV_IMG_DECLARE(ui_img_icon6_png);    // assets/icon6.png
LV_IMG_DECLARE(ui_img_flashlight_png);    // assets/Flashlight.png
extern const lv_img_dsc_t * ui_imgset_icon[6] ;
// FONTS
LV_FONT_DECLARE(ui_font_CLOCKfont);
LV_FONT_DECLARE(ui_font_CLOCKFont2);
LV_FONT_DECLARE(ui_font_SongDenisty16);

// UI INIT
void ui_init(void);



extern lv_group_t* grouphand;
extern float dispnow;



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
