// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3

#include "ui.h"

void ui_AiChat_screen_init(void) {
  ui_AiChat = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_AiChat, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_AiChat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_AiChat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);
  ui_object_set_themeable_style_property(ui_AiChat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask2);
  lv_obj_set_style_bg_main_stop(ui_AiChat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_AiChat, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_AiChat, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container10 = lv_obj_create(ui_AiChat);
  lv_obj_remove_style_all(ui_Container10);
  lv_obj_set_width(ui_Container10, 111);
  lv_obj_set_height(ui_Container10, 279);
  lv_obj_set_x(ui_Container10, 66);
  lv_obj_set_y(ui_Container10, -1);
  lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_Container10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Container10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);
  ui_object_set_themeable_style_property(ui_Container10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Back);
  lv_obj_set_style_bg_main_stop(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Container10, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_Container10, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_aichattext1 = lv_textarea_create(ui_AiChat);
  lv_obj_set_width(ui_aichattext1, 180);
  lv_obj_set_height(ui_aichattext1, 200);
  lv_obj_set_x(ui_aichattext1, 0);
  lv_obj_set_y(ui_aichattext1, -25);
  lv_obj_set_align(ui_aichattext1, LV_ALIGN_CENTER);
  lv_textarea_set_placeholder_text(ui_aichattext1, "...");
  ui_object_set_themeable_style_property(ui_aichattext1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_aichattext1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_aichattext1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_aichattext1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_aichattext1, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_text_color(ui_aichattext1, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_aichattext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

  ui_aichattext2 = lv_textarea_create(ui_AiChat);
  lv_obj_set_width(ui_aichattext2, 126);
  lv_obj_set_height(ui_aichattext2, LV_SIZE_CONTENT);  /// 29
  lv_obj_set_x(ui_aichattext2, -28);
  lv_obj_set_y(ui_aichattext2, 100);
  lv_obj_set_align(ui_aichattext2, LV_ALIGN_CENTER);
  lv_textarea_set_placeholder_text(ui_aichattext2, "listening...");
  lv_textarea_set_one_line(ui_aichattext2, true);
  ui_object_set_themeable_style_property(ui_aichattext2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_aichattext2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_aichattext2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_aichattext2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_aichattext2, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);


  lv_obj_set_style_text_color(ui_aichattext2, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_aichattext2, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

  ui_aichatSpinner1 = lv_spinner_create(ui_AiChat, 1000, 90);
  lv_obj_set_width(ui_aichatSpinner1, 40);
  lv_obj_set_height(ui_aichatSpinner1, 40);
  lv_obj_set_x(ui_aichatSpinner1, 66);
  lv_obj_set_y(ui_aichatSpinner1, 100);
  lv_obj_set_align(ui_aichatSpinner1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_aichatSpinner1, LV_OBJ_FLAG_CLICKABLE);  /// Flags

  ui_object_set_themeable_style_property(ui_aichatSpinner1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_aichatSpinner1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                         _ui_theme_alpha_Front);
  lv_obj_set_style_arc_width(ui_aichatSpinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);



  ui_ButtonBACK4 = lv_btn_create(ui_AiChat);
  lv_obj_set_width(ui_ButtonBACK4, 53);
  lv_obj_set_height(ui_ButtonBACK4, 50);
  lv_obj_set_x(ui_ButtonBACK4, -90);
  lv_obj_set_y(ui_ButtonBACK4, -13);
  lv_obj_set_align(ui_ButtonBACK4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonBACK4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonBACK4, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ButtonBACK4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonBACK4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ChatBtn = lv_btn_create(ui_AiChat);
  lv_obj_set_width(ui_ChatBtn, 53);
  lv_obj_set_height(ui_ChatBtn, 50);
  lv_obj_set_x(ui_ChatBtn, 90);
  lv_obj_set_y(ui_ChatBtn, -13);
  lv_obj_set_align(ui_ChatBtn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ChatBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ChatBtn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ChatBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ChatBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_ButtonBACK4, ui_event_ButtonBACK4, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ChatBtn, ui_event_ChatBtn, LV_EVENT_ALL, NULL);

  lv_textarea_set_text(ui_aichattext1, "获取鉴权信息...");
  getAccess();
}
