// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3-2

#include "ui.h"
void printEnabledAlarms() {
  lv_obj_clear_state(ui_Alarmkey, LV_STATE_CHECKED);
  lv_obj_clear_state(ui_Alarmkey2, LV_STATE_CHECKED);
  lv_obj_clear_state(ui_Alarmkey3, LV_STATE_CHECKED);
  for (int i = 1; i <= 3; i++) {
    if (alarmumget() & (1 << (i - 1))) {  // 检查第 i 个闹钟是否启用
      switch (i) {
        case 1: lv_obj_add_state(ui_Alarmkey, LV_STATE_CHECKED); break;
        case 2: lv_obj_add_state(ui_Alarmkey2, LV_STATE_CHECKED); break;
        case 3: lv_obj_add_state(ui_Alarmkey3, LV_STATE_CHECKED); break;
      }
    }
  }
}

void ui_ALARM_screen_init(void) {

  getalarmall(&hour1, &min1, &hour2, &min2, &hour3, &min3);
  ui_ALARM = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_ALARM, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_ALARM, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_ALARM, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);
  ui_object_set_themeable_style_property(ui_ALARM, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask2);
  lv_obj_set_style_bg_main_stop(ui_ALARM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_ALARM, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_ALARM, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container13 = lv_obj_create(ui_ALARM);
  lv_obj_remove_style_all(ui_Container13);
  lv_obj_set_width(ui_Container13, 111);
  lv_obj_set_height(ui_Container13, 279);
  lv_obj_set_x(ui_Container13, 66);
  lv_obj_set_y(ui_Container13, -1);
  lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_Container13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Container13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);
  ui_object_set_themeable_style_property(ui_Container13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Back);
  lv_obj_set_style_bg_main_stop(ui_Container13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Container13, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_Container13, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container15 = lv_obj_create(ui_ALARM);
  lv_obj_remove_style_all(ui_Container15);
  lv_obj_set_width(ui_Container15, 200);
  lv_obj_set_height(ui_Container15, 220);
  lv_obj_set_x(ui_Container15, 0);
  lv_obj_set_y(ui_Container15, 1);
  lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Container15, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_Container15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask1);
  ui_object_set_themeable_style_property(ui_Container15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask1);
  ui_object_set_themeable_style_property(ui_Container15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask1);
  lv_obj_set_style_bg_grad_dir(ui_Container15, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonBACK9 = lv_btn_create(ui_ALARM);
  lv_obj_set_width(ui_ButtonBACK9, 53);
  lv_obj_set_height(ui_ButtonBACK9, 30);
  lv_obj_set_x(ui_ButtonBACK9, 0);
  lv_obj_set_y(ui_ButtonBACK9, 89);
  lv_obj_set_align(ui_ButtonBACK9, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonBACK9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonBACK9, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_ButtonBACK9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_ButtonBACK9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_ButtonBACK9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_ButtonBACK9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_ButtonBACK9, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_backtext4 = lv_label_create(ui_ButtonBACK9);
  lv_obj_set_width(ui_backtext4, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_backtext4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_backtext4, LV_ALIGN_CENTER);
  lv_label_set_text(ui_backtext4, "返回");
  ui_object_set_themeable_style_property(ui_backtext4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_backtext4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_Alarm1 = lv_obj_create(ui_ALARM);
  lv_obj_set_width(ui_Alarm1, 180);
  lv_obj_set_height(ui_Alarm1, 50);
  lv_obj_set_x(ui_Alarm1, 0);
  lv_obj_set_y(ui_Alarm1, -80);
  lv_obj_set_align(ui_Alarm1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Alarm1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Alarm1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Alarmbtn = lv_btn_create(ui_Alarm1);
  lv_obj_set_width(ui_Alarmbtn, 93);
  lv_obj_set_height(ui_Alarmbtn, 36);
  lv_obj_set_x(ui_Alarmbtn, -31);
  lv_obj_set_y(ui_Alarmbtn, 0);
  lv_obj_set_align(ui_Alarmbtn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Alarmbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Alarmbtn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_radius(ui_Alarmbtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_Alarmbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_Alarmbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_Alarmtext = lv_label_create(ui_Alarmbtn);
  lv_obj_set_width(ui_Alarmtext, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Alarmtext, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Alarmtext, LV_ALIGN_CENTER);

  gettimeC(hour1, min1, 1);

  lv_obj_set_style_text_font(ui_Alarmtext, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Alarmkey = lv_switch_create(ui_Alarm1);
  lv_obj_set_width(ui_Alarmkey, 50);
  lv_obj_set_height(ui_Alarmkey, 30);
  lv_obj_set_x(ui_Alarmkey, 56);
  lv_obj_set_y(ui_Alarmkey, 0);
  lv_obj_set_align(ui_Alarmkey, LV_ALIGN_CENTER);

  ui_object_set_themeable_style_property(ui_Alarmkey, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_Alarmkey, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);

  ui_object_set_themeable_style_property(ui_Alarmkey, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_Alarmkey, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_Alarm2 = lv_obj_create(ui_ALARM);
  lv_obj_set_width(ui_Alarm2, 180);
  lv_obj_set_height(ui_Alarm2, 50);
  lv_obj_set_x(ui_Alarm2, 0);
  lv_obj_set_y(ui_Alarm2, -20);
  lv_obj_set_align(ui_Alarm2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Alarm2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Alarm2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Alarmbtn2 = lv_btn_create(ui_Alarm2);
  lv_obj_set_width(ui_Alarmbtn2, 93);
  lv_obj_set_height(ui_Alarmbtn2, 36);
  lv_obj_set_x(ui_Alarmbtn2, -31);
  lv_obj_set_y(ui_Alarmbtn2, 0);
  lv_obj_set_align(ui_Alarmbtn2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Alarmbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Alarmbtn2, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_radius(ui_Alarmbtn2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_Alarmbtn2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_Alarmbtn2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_Alarmtext2 = lv_label_create(ui_Alarmbtn2);
  lv_obj_set_width(ui_Alarmtext2, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Alarmtext2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Alarmtext2, LV_ALIGN_CENTER);

  gettimeC(hour2, min2, 2);

  lv_obj_set_style_text_font(ui_Alarmtext2, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Alarmkey2 = lv_switch_create(ui_Alarm2);
  lv_obj_set_width(ui_Alarmkey2, 50);
  lv_obj_set_height(ui_Alarmkey2, 30);
  lv_obj_set_x(ui_Alarmkey2, 56);
  lv_obj_set_y(ui_Alarmkey2, -2);
  lv_obj_set_align(ui_Alarmkey2, LV_ALIGN_CENTER);

  ui_object_set_themeable_style_property(ui_Alarmkey2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_Alarmkey2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);

  ui_object_set_themeable_style_property(ui_Alarmkey2, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_Alarmkey2, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_Alarm3 = lv_obj_create(ui_ALARM);
  lv_obj_set_width(ui_Alarm3, 180);
  lv_obj_set_height(ui_Alarm3, 50);
  lv_obj_set_x(ui_Alarm3, 0);
  lv_obj_set_y(ui_Alarm3, 40);
  lv_obj_set_align(ui_Alarm3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Alarm3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Alarm3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Alarmbtn3 = lv_btn_create(ui_Alarm3);
  lv_obj_set_width(ui_Alarmbtn3, 93);
  lv_obj_set_height(ui_Alarmbtn3, 36);
  lv_obj_set_x(ui_Alarmbtn3, -31);
  lv_obj_set_y(ui_Alarmbtn3, 0);
  lv_obj_set_align(ui_Alarmbtn3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Alarmbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Alarmbtn3, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_radius(ui_Alarmbtn3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_Alarmbtn3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_Alarmbtn3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_Alarmtext3 = lv_label_create(ui_Alarmbtn3);
  lv_obj_set_width(ui_Alarmtext3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Alarmtext3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Alarmtext3, LV_ALIGN_CENTER);

  gettimeC(hour3, min3, 3);

  lv_obj_set_style_text_font(ui_Alarmtext3, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Alarmkey3 = lv_switch_create(ui_Alarm3);
  lv_obj_set_width(ui_Alarmkey3, 50);
  lv_obj_set_height(ui_Alarmkey3, 30);
  lv_obj_set_x(ui_Alarmkey3, 56);
  lv_obj_set_y(ui_Alarmkey3, 0);
  lv_obj_set_align(ui_Alarmkey3, LV_ALIGN_CENTER);

  ui_object_set_themeable_style_property(ui_Alarmkey3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_Alarmkey3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);

  ui_object_set_themeable_style_property(ui_Alarmkey3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_Alarmkey3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  lv_obj_add_event_cb(ui_ButtonBACK9, ui_event_ButtonBACK9, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Alarmbtn, ui_event_Alarmbtn, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Alarmkey, ui_event_Alarmkey, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Alarmbtn2, ui_event_Alarmbtn2, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Alarmkey2, ui_event_Alarmkey2, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Alarmbtn3, ui_event_Alarmbtn3, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Alarmkey3, ui_event_Alarmkey3, LV_EVENT_ALL, NULL);
  printEnabledAlarms();



  lv_group_remove_all_objs(grouphand);
  lv_group_add_obj(grouphand, ui_Alarmbtn);
  lv_group_add_obj(grouphand, ui_Alarmkey);
  lv_group_add_obj(grouphand, ui_Alarmbtn2);
  lv_group_add_obj(grouphand, ui_Alarmkey2);
  lv_group_add_obj(grouphand, ui_Alarmbtn3);
  lv_group_add_obj(grouphand, ui_Alarmkey3);
  lv_group_add_obj(grouphand, ui_ButtonBACK9);
}
