// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3

#include "ui.h"

void ui_CALENDAR_screen_init(void) {
  ui_CALENDAR = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_CALENDAR, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_CALENDAR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_CALENDAR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);
  ui_object_set_themeable_style_property(ui_CALENDAR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask2);
  lv_obj_set_style_bg_main_stop(ui_CALENDAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_CALENDAR, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_CALENDAR, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container4 = lv_obj_create(ui_CALENDAR);
  lv_obj_remove_style_all(ui_Container4);
  lv_obj_set_width(ui_Container4, 111);
  lv_obj_set_height(ui_Container4, 279);
  lv_obj_set_x(ui_Container4, 66);
  lv_obj_set_y(ui_Container4, -1);
  lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);
  ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Back);
  lv_obj_set_style_bg_main_stop(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Container4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_Container4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Calendar1 = lv_calendar_create(ui_CALENDAR);
  int Y = 2024;
  int M = 12;
  int D = 1;
  getDc(&Y, &M, &D);


  lv_obj_t* ui_Calendar1_header = lv_calendar_header_dropdown_create(ui_Calendar1);
  lv_calendar_set_today_date(ui_Calendar1, Y, M, D);
  lv_calendar_set_showed_date(ui_Calendar1, Y, M);


  lv_obj_set_width(ui_Calendar1, 230);
  lv_obj_set_height(ui_Calendar1, 240);
  lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
  ui_object_set_themeable_style_property(ui_Calendar1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Calendar1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);



  ui_ButtonDown2 = lv_btn_create(ui_CALENDAR);
  lv_obj_set_width(ui_ButtonDown2, 44);
  lv_obj_set_height(ui_ButtonDown2, 50);
  lv_obj_set_x(ui_ButtonDown2, 80);
  lv_obj_set_y(ui_ButtonDown2, 90);
  lv_obj_set_align(ui_ButtonDown2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonDown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonDown2, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ButtonDown2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonDown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonBACK5 = lv_btn_create(ui_CALENDAR);
  lv_obj_set_width(ui_ButtonBACK5, 53);
  lv_obj_set_height(ui_ButtonBACK5, 50);
  lv_obj_set_x(ui_ButtonBACK5, -90);
  lv_obj_set_y(ui_ButtonBACK5, -13);
  lv_obj_set_align(ui_ButtonBACK5, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonBACK5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonBACK5, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ButtonBACK5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonBACK5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


  ui_ButtonUp2 = lv_btn_create(ui_CALENDAR);
  lv_obj_set_width(ui_ButtonUp2, 44);
  lv_obj_set_height(ui_ButtonUp2, 50);
  lv_obj_set_x(ui_ButtonUp2, 80);
  lv_obj_set_y(ui_ButtonUp2, -90);
  lv_obj_set_align(ui_ButtonUp2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonUp2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonUp2, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ButtonUp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonUp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonCen2 = lv_btn_create(ui_CALENDAR);
  lv_obj_set_width(ui_ButtonCen2, 53);
  lv_obj_set_height(ui_ButtonCen2, 50);
  lv_obj_set_x(ui_ButtonCen2, 88);
  lv_obj_set_y(ui_ButtonCen2, -13);
  lv_obj_set_align(ui_ButtonCen2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonCen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonCen2, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ButtonCen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonCen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_ButtonDown2, ui_event_ButtonDown2, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ButtonUp2, ui_event_ButtonUp2, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ButtonBACK5, ui_event_ButtonBACK5, LV_EVENT_ALL, NULL);
 lv_obj_add_event_cb(ui_ButtonCen2, ui_event_ButtonCen2, LV_EVENT_ALL, NULL);
}
