// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3


#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
void Chatdelete();
void setBLight(lv_event_t * e);
void SettingStart(lv_event_t * e);
void Wifistart(lv_event_t * e);
void getTWifi(lv_event_t * e);
void SetClock(lv_event_t * e);
void setHour0(lv_event_t * e);
void setHour1(lv_event_t * e);
void setMinu0(lv_event_t * e);
void setMinu1(lv_event_t * e);
void gotuofunc(lv_event_t * e);
void ChatClick(lv_event_t * e);
void setAilocal(lv_event_t * e);
void setlightU(lv_event_t * e);
void setlightD(lv_event_t * e);
void setAssistantWebRecording(int x);
extern int chatstate;
extern int flashlightval;
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
