// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3

#include "ui.h"

void ui_LIGHT_screen_init(void)
{
    ui_LIGHT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LIGHT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_LIGHT, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Back);
    ui_object_set_themeable_style_property(ui_LIGHT, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Back);
    ui_object_set_themeable_style_property(ui_LIGHT, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_Mask2);
    lv_obj_set_style_bg_main_stop(ui_LIGHT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_LIGHT, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LIGHT, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LIGHT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBACK7 = lv_btn_create(ui_LIGHT);
    lv_obj_set_width(ui_ButtonBACK7, 53);
    lv_obj_set_height(ui_ButtonBACK7, 50);
    lv_obj_set_x(ui_ButtonBACK7, -90);
    lv_obj_set_y(ui_ButtonBACK7, -13);
    lv_obj_set_align(ui_ButtonBACK7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBACK7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBACK7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBACK7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBACK7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonUp5 = lv_btn_create(ui_LIGHT);
    lv_obj_set_width(ui_ButtonUp5, 44);
    lv_obj_set_height(ui_ButtonUp5, 50);
    lv_obj_set_x(ui_ButtonUp5, 80);
    lv_obj_set_y(ui_ButtonUp5, -90);
    lv_obj_set_align(ui_ButtonUp5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUp5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUp5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonUp5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonUp5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDown5 = lv_btn_create(ui_LIGHT);
    lv_obj_set_width(ui_ButtonDown5, 44);
    lv_obj_set_height(ui_ButtonDown5, 50);
    lv_obj_set_x(ui_ButtonDown5, 80);
    lv_obj_set_y(ui_ButtonDown5, 90);
    lv_obj_set_align(ui_ButtonDown5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDown5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonDown5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonDown5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDown5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_LIGHT);
    lv_img_set_src(ui_Image1, &ui_img_flashlight_png);
    lv_obj_set_width(ui_Image1, lv_pct(100));
    lv_obj_set_height(ui_Image1, lv_pct(100));
    lv_obj_set_x(ui_Image1, -4);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_Image1, 350, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonBACK7, ui_event_ButtonBACK7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonUp5, ui_event_ButtonUp5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonDown5, ui_event_ButtonDown5, LV_EVENT_ALL, NULL);

}
