// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3-2

#include "ui.h"

void ui_REMINDER_screen_init(void) {
  
  ui_REMINDER = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_REMINDER, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_REMINDER, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_REMINDER, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);
  ui_object_set_themeable_style_property(ui_REMINDER, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask2);
  lv_obj_set_style_bg_main_stop(ui_REMINDER, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_REMINDER, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_REMINDER, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container12 = lv_obj_create(ui_REMINDER);
  lv_obj_remove_style_all(ui_Container12);
  lv_obj_set_width(ui_Container12, 111);
  lv_obj_set_height(ui_Container12, 279);
  lv_obj_set_x(ui_Container12, 66);
  lv_obj_set_y(ui_Container12, -1);
  lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_Container12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Container12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);
  ui_object_set_themeable_style_property(ui_Container12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Back);
  lv_obj_set_style_bg_main_stop(ui_Container12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Container12, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_Container12, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonBACK8 = lv_btn_create(ui_REMINDER);
  lv_obj_set_width(ui_ButtonBACK8, 53);
  lv_obj_set_height(ui_ButtonBACK8, 30);
  lv_obj_set_x(ui_ButtonBACK8, 0);
  lv_obj_set_y(ui_ButtonBACK8, 89);
  lv_obj_set_align(ui_ButtonBACK8, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonBACK8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonBACK8, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_ButtonBACK8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_ButtonBACK8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_ButtonBACK8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_ButtonBACK8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_ButtonBACK8, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_backtext3 = lv_label_create(ui_ButtonBACK8);
  lv_obj_set_width(ui_backtext3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_backtext3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_backtext3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_backtext3, "返回");
  ui_object_set_themeable_style_property(ui_backtext3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_backtext3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_TextArea1 = lv_textarea_create(ui_REMINDER);
  lv_obj_set_width(ui_TextArea1, 200);
  lv_obj_set_height(ui_TextArea1, 120);
  lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
  getReminderfromEEPROM();
  //lv_textarea_set_text(ui_TextArea1, reminderC[0]);
  lv_textarea_set_placeholder_text(ui_TextArea1, "change list to refresh...");
  lv_obj_set_style_text_font(ui_TextArea1, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);



  ui_MemoRefresh = lv_btn_create(ui_REMINDER);
  lv_obj_set_width(ui_MemoRefresh, 53);
  lv_obj_set_height(ui_MemoRefresh, 30);
  lv_obj_set_x(ui_MemoRefresh, 70);
  lv_obj_set_y(ui_MemoRefresh, -100);
  lv_obj_set_align(ui_MemoRefresh, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_MemoRefresh, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_MemoRefresh, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_MemoRefresh, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_MemoRefresh, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_MemoRefresh, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_MemoRefresh, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_MemoRefresh, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_MemoRefreshtext = lv_label_create(ui_MemoRefresh);
  lv_obj_set_width(ui_MemoRefreshtext, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_MemoRefreshtext, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_MemoRefreshtext, LV_ALIGN_CENTER);
  lv_label_set_text(ui_MemoRefreshtext, "刷新");
  ui_object_set_themeable_style_property(ui_MemoRefreshtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_MemoRefreshtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_reminderDropdown2 = lv_dropdown_create(ui_REMINDER);
  lv_dropdown_set_options(ui_reminderDropdown2, "备忘1\n备忘2\n备忘3\n备忘4\n备忘5");
  lv_obj_set_width(ui_reminderDropdown2, 125);
  lv_obj_set_height(ui_reminderDropdown2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_reminderDropdown2, -40);
  lv_obj_set_y(ui_reminderDropdown2, -100);
  lv_obj_set_align(ui_reminderDropdown2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_reminderDropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_set_style_text_font(ui_reminderDropdown2, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_text_font(ui_reminderDropdown2, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_text_font(lv_dropdown_get_list(ui_reminderDropdown2), &ui_font_SongDenisty16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_text_font(lv_dropdown_get_list(ui_reminderDropdown2), &ui_font_SongDenisty16,
                             LV_PART_SELECTED | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_ButtonBACK8, ui_event_ButtonBACK8, LV_EVENT_ALL, NULL);

  lv_obj_add_event_cb(ui_MemoRefresh, ui_event_MemoRefresh, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_reminderDropdown2, ui_event_reminderDropdown2, LV_EVENT_ALL, NULL);
  lv_group_remove_all_objs(grouphand);

  lv_group_add_obj(grouphand, ui_reminderDropdown2);
  lv_group_add_obj(grouphand, ui_MemoRefresh);
  lv_group_add_obj(grouphand, ui_ButtonBACK8);
}
