// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3

#include "ui.h"

void ui_SETTING_screen_init(void) {
  ui_SETTING = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_SETTING, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_SETTING, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_SETTING, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);
  ui_object_set_themeable_style_property(ui_SETTING, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask2);
  lv_obj_set_style_bg_main_stop(ui_SETTING, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_SETTING, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_SETTING, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container6 = lv_obj_create(ui_SETTING);
  lv_obj_remove_style_all(ui_Container6);
  lv_obj_set_width(ui_Container6, 111);
  lv_obj_set_height(ui_Container6, 279);
  lv_obj_set_x(ui_Container6, 66);
  lv_obj_set_y(ui_Container6, -1);
  lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);
  ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Back);
  lv_obj_set_style_bg_main_stop(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Container6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_Container6, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container7 = lv_obj_create(ui_SETTING);
  lv_obj_remove_style_all(ui_Container7);
  lv_obj_set_width(ui_Container7, 200);
  lv_obj_set_height(ui_Container7, 220);
  lv_obj_set_x(ui_Container7, 0);
  lv_obj_set_y(ui_Container7, 1);
  lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Container7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_Container7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask1);
  ui_object_set_themeable_style_property(ui_Container7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask1);
  ui_object_set_themeable_style_property(ui_Container7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask1);
  lv_obj_set_style_bg_grad_dir(ui_Container7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_BLslider = lv_slider_create(ui_SETTING);
  lv_slider_set_range(ui_BLslider, 1, 20);
  lv_slider_set_value(ui_BLslider, leddut / 10, LV_ANIM_OFF);
  if (lv_slider_get_mode(ui_BLslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BLslider, 0, LV_ANIM_OFF);
  lv_obj_set_width(ui_BLslider, 109);
  lv_obj_set_height(ui_BLslider, 10);
  lv_obj_set_x(ui_BLslider, 27);
  lv_obj_set_y(ui_BLslider, -78);
  lv_obj_set_align(ui_BLslider, LV_ALIGN_CENTER);
  lv_obj_set_style_bg_color(ui_BLslider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_BLslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_object_set_themeable_style_property(ui_BLslider, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_BLslider, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);

  ui_object_set_themeable_style_property(ui_BLslider, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_BLslider, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_ButtonBACK1 = lv_btn_create(ui_SETTING);
  lv_obj_set_width(ui_ButtonBACK1, 53);
  lv_obj_set_height(ui_ButtonBACK1, 30);
  lv_obj_set_x(ui_ButtonBACK1, 0);
  lv_obj_set_y(ui_ButtonBACK1, 89);
  lv_obj_set_align(ui_ButtonBACK1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonBACK1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonBACK1, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_ButtonBACK1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_ButtonBACK1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_ButtonBACK1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_ButtonBACK1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_ButtonBACK1, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_backtext = lv_label_create(ui_ButtonBACK1);
  lv_obj_set_width(ui_backtext, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_backtext, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_backtext, LV_ALIGN_CENTER);
  lv_label_set_text(ui_backtext, "返回");
  ui_object_set_themeable_style_property(ui_backtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_backtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_BLtext = lv_label_create(ui_SETTING);
  lv_obj_set_width(ui_BLtext, 47);
  lv_obj_set_height(ui_BLtext, 18);
  lv_obj_set_x(ui_BLtext, -60);
  lv_obj_set_y(ui_BLtext, -78);
  lv_obj_set_align(ui_BLtext, LV_ALIGN_CENTER);
  lv_label_set_text(ui_BLtext, "背光");
  ui_object_set_themeable_style_property(ui_BLtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_BLtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);
  lv_obj_set_style_text_align(ui_BLtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_BLtext, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_BLtext, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_BLtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_BLtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_ButtonGETTIME = lv_btn_create(ui_SETTING);
  lv_obj_set_width(ui_ButtonGETTIME, 168);
  lv_obj_set_height(ui_ButtonGETTIME, 30);
  lv_obj_set_align(ui_ButtonGETTIME, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonGETTIME, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonGETTIME, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_ButtonGETTIME, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_ButtonGETTIME, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_ButtonGETTIME, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_ButtonGETTIME, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_ButtonGETTIME, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_GetTimetext = lv_label_create(ui_ButtonGETTIME);
  lv_obj_set_width(ui_GetTimetext, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_GetTimetext, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_GetTimetext, LV_ALIGN_CENTER);
  lv_label_set_text(ui_GetTimetext, "校时");
  ui_object_set_themeable_style_property(ui_GetTimetext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_GetTimetext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_SETTINGtext = lv_label_create(ui_SETTING);
  lv_obj_set_width(ui_SETTINGtext, 117);
  lv_obj_set_height(ui_SETTINGtext, 18);
  lv_obj_set_x(ui_SETTINGtext, -26);
  lv_obj_set_y(ui_SETTINGtext, 45);
  lv_obj_set_align(ui_SETTINGtext, LV_ALIGN_CENTER);
  lv_label_set_text(ui_SETTINGtext, "网页端设置");
  ui_object_set_themeable_style_property(ui_SETTINGtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_SETTINGtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);
  lv_obj_set_style_text_align(ui_SETTINGtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_SETTINGtext, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_SETTINGtext, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_SETTINGtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_SETTINGtext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_SETTINGKEY = lv_switch_create(ui_SETTING);
  lv_obj_set_width(ui_SETTINGKEY, 50);
  lv_obj_set_height(ui_SETTINGKEY, 25);
  lv_obj_set_x(ui_SETTINGKEY, 64);
  lv_obj_set_y(ui_SETTINGKEY, 45);
  lv_obj_set_align(ui_SETTINGKEY, LV_ALIGN_CENTER);

  ui_object_set_themeable_style_property(ui_SETTINGKEY, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_SETTINGKEY, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);

  ui_object_set_themeable_style_property(ui_SETTINGKEY, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_SETTINGKEY, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_WIFItext = lv_label_create(ui_SETTING);
  lv_obj_set_width(ui_WIFItext, 119);
  lv_obj_set_height(ui_WIFItext, 18);
  lv_obj_set_x(ui_WIFItext, -27);
  lv_obj_set_y(ui_WIFItext, -40);
  lv_obj_set_align(ui_WIFItext, LV_ALIGN_CENTER);
  if (Wificheck() == 0) wifistatu = 0;
  else wifistatu = 1;
  if (wifistatu == 0) lv_label_set_text(ui_WIFItext, " WIFI:未连接");
  if (wifistatu == 1) lv_label_set_text(ui_WIFItext, " WIFI:已连接");
  ui_object_set_themeable_style_property(ui_WIFItext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_WIFItext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);
  lv_obj_set_style_text_align(ui_WIFItext, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_WIFItext, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_WIFItext, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_WIFItext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_WIFItext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);

  ui_WIFIKEY = lv_switch_create(ui_SETTING);
  lv_obj_set_width(ui_WIFIKEY, 50);
  lv_obj_set_height(ui_WIFIKEY, 25);
  lv_obj_set_x(ui_WIFIKEY, 64);
  lv_obj_set_y(ui_WIFIKEY, -40);
  lv_obj_set_align(ui_WIFIKEY, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_WIFIKEY, LV_OBJ_FLAG_CLICKABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_WIFIKEY, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_WIFIKEY, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);

  ui_object_set_themeable_style_property(ui_WIFIKEY, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_WIFIKEY, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  if (wifistatu == 1) lv_obj_add_state(ui_WIFIKEY, LV_STATE_CHECKED);  // 开
  lv_obj_add_event_cb(ui_BLslider, ui_event_BLslider, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ButtonBACK1, ui_event_ButtonBACK1, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ButtonGETTIME, ui_event_ButtonGETTIME, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_SETTINGKEY, ui_event_SETTINGKEY, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_WIFIKEY, ui_event_WIFIKEY, LV_EVENT_ALL, NULL);
  lv_group_remove_all_objs(grouphand);

  lv_group_add_obj(grouphand, ui_BLslider);
  lv_group_add_obj(grouphand, ui_WIFIKEY);
  lv_group_add_obj(grouphand, ui_ButtonGETTIME);
  lv_group_add_obj(grouphand, ui_SETTINGKEY);
  lv_group_add_obj(grouphand, ui_ButtonBACK1);
}
