// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3

#include "ui.h"

void ui_SETTIME_screen_init(void) {
  ui_SETTIME = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_SETTIME, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_SETTIME, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_SETTIME, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Back);
  ui_object_set_themeable_style_property(ui_SETTIME, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask2);
  lv_obj_set_style_bg_main_stop(ui_SETTIME, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_SETTIME, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_SETTIME, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container8 = lv_obj_create(ui_SETTIME);
  lv_obj_remove_style_all(ui_Container8);
  lv_obj_set_width(ui_Container8, 111);
  lv_obj_set_height(ui_Container8, 279);
  lv_obj_set_x(ui_Container8, 66);
  lv_obj_set_y(ui_Container8, -1);
  lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  ui_object_set_themeable_style_property(ui_Container8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Container8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);
  ui_object_set_themeable_style_property(ui_Container8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Back);
  lv_obj_set_style_bg_main_stop(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Container8, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_Container8, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container9 = lv_obj_create(ui_SETTIME);
  lv_obj_remove_style_all(ui_Container9);
  lv_obj_set_width(ui_Container9, 200);
  lv_obj_set_height(ui_Container9, 220);
  lv_obj_set_x(ui_Container9, 0);
  lv_obj_set_y(ui_Container9, 1);
  lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Container9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(ui_Container9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask1);
  ui_object_set_themeable_style_property(ui_Container9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask1);
  ui_object_set_themeable_style_property(ui_Container9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                         _ui_theme_color_Mask1);
  lv_obj_set_style_bg_grad_dir(ui_Container9, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonDown4 = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_ButtonDown4, 44);
  lv_obj_set_height(ui_ButtonDown4, 50);
  lv_obj_set_x(ui_ButtonDown4, 80);
  lv_obj_set_y(ui_ButtonDown4, 90);
  lv_obj_set_align(ui_ButtonDown4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonDown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonDown4, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ButtonDown4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonDown4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonUp4 = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_ButtonUp4, 44);
  lv_obj_set_height(ui_ButtonUp4, 50);
  lv_obj_set_x(ui_ButtonUp4, 80);
  lv_obj_set_y(ui_ButtonUp4, -90);
  lv_obj_set_align(ui_ButtonUp4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonUp4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonUp4, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ButtonUp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonUp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonCen4 = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_ButtonCen4, 53);
  lv_obj_set_height(ui_ButtonCen4, 50);
  lv_obj_set_x(ui_ButtonCen4, 88);
  lv_obj_set_y(ui_ButtonCen4, -13);
  lv_obj_set_align(ui_ButtonCen4, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonCen4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonCen4, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_ButtonCen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ButtonCen4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ButtonBACK2 = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_ButtonBACK2, 53);
  lv_obj_set_height(ui_ButtonBACK2, 30);
  lv_obj_set_x(ui_ButtonBACK2, 0);
  lv_obj_set_y(ui_ButtonBACK2, 89);
  lv_obj_set_align(ui_ButtonBACK2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ButtonBACK2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ButtonBACK2, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_ButtonBACK2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_ButtonBACK2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_ButtonBACK2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_ButtonBACK2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_ButtonBACK2, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_backtext1 = lv_label_create(ui_ButtonBACK2);
  lv_obj_set_width(ui_backtext1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_backtext1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_backtext1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_backtext1, "返回");
  ui_object_set_themeable_style_property(ui_backtext1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_backtext1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_getTWifiBtn = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_getTWifiBtn, 84);
  lv_obj_set_height(ui_getTWifiBtn, 30);
  lv_obj_set_x(ui_getTWifiBtn, 50);
  lv_obj_set_y(ui_getTWifiBtn, 40);
  lv_obj_set_align(ui_getTWifiBtn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_getTWifiBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_getTWifiBtn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_getTWifiBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_getTWifiBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_getTWifiBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_getTWifiBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_getTWifiBtn, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_getTWifi = lv_label_create(ui_getTWifiBtn);
  lv_obj_set_width(ui_getTWifi, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_getTWifi, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_getTWifi, LV_ALIGN_CENTER);
  /*if(settimemod==0)*/ lv_label_set_text(ui_getTWifi, "网络校时");
  //else lv_label_set_text(ui_getTWifi, "启用");
  ui_object_set_themeable_style_property(ui_getTWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_getTWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);
  timeset[0] = 0;
  timeset[1] = 0;
  timeset[2] = 0;
  timeset[3] = 0;
  switch (settimemod) {
    case 1:
      timeset[0] = hour1 / 10;  // 十位小时
      timeset[1] = hour1 % 10;  // 个位小时
      timeset[2] = min1 / 10;   // 十位分钟
      timeset[3] = min1 % 10;   // 个位分钟
      break;
    case 2:
      timeset[0] = hour2 / 10;  // 十位小时
      timeset[1] = hour2 % 10;  // 个位小时
      timeset[2] = min2 / 10;   // 十位分钟
      timeset[3] = min2 % 10;   // 个位分钟
      break;
    case 3:
      timeset[0] = hour3 / 10;  // 十位小时
      timeset[1] = hour3 % 10;  // 个位小时
      timeset[2] = min3 / 10;   // 十位分钟
      timeset[3] = min3 % 10;   // 个位分钟
      break;
    default: break;
  }
  ui_timeSetBtn = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_timeSetBtn, 84);
  lv_obj_set_height(ui_timeSetBtn, 30);
  lv_obj_set_x(ui_timeSetBtn, -50);
  lv_obj_set_y(ui_timeSetBtn, 40);
  lv_obj_set_align(ui_timeSetBtn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_timeSetBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_timeSetBtn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_timeSetBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_timeSetBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Front);
  ui_object_set_themeable_style_property(ui_timeSetBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Back);
  ui_object_set_themeable_style_property(ui_timeSetBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Back);
  lv_obj_set_style_text_font(ui_timeSetBtn, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_timeSet = lv_label_create(ui_timeSetBtn);
  lv_obj_set_width(ui_timeSet, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_timeSet, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_timeSet, LV_ALIGN_CENTER);
  lv_label_set_text(ui_timeSet, "设定");
  ui_object_set_themeable_style_property(ui_timeSet, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_timeSet, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_Hour0 = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_Hour0, 44);
  lv_obj_set_height(ui_Hour0, 58);
  lv_obj_set_x(ui_Hour0, -75);
  lv_obj_set_y(ui_Hour0, -10);
  lv_obj_set_align(ui_Hour0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Hour0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Hour0, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_Hour0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Hour0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_hour0label = lv_label_create(ui_Hour0);
  lv_obj_set_width(ui_hour0label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_hour0label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_hour0label, LV_ALIGN_CENTER);


  setTimechar(timeset[0], 0);
  ui_object_set_themeable_style_property(ui_hour0label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_hour0label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Front);
  lv_obj_set_style_text_font(ui_hour0label, &ui_font_CLOCKFont2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Hour1 = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_Hour1, 44);
  lv_obj_set_height(ui_Hour1, 58);
  lv_obj_set_x(ui_Hour1, -29);
  lv_obj_set_y(ui_Hour1, -10);
  lv_obj_set_align(ui_Hour1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Hour1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Hour1, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_Hour1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Hour1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_hour1label = lv_label_create(ui_Hour1);
  lv_obj_set_width(ui_hour1label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_hour1label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_hour1label, LV_ALIGN_CENTER);

  setTimechar(timeset[1], 1);

  ui_object_set_themeable_style_property(ui_hour1label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_hour1label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Front);
  lv_obj_set_style_text_font(ui_hour1label, &ui_font_CLOCKFont2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Min0 = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_Min0, 44);
  lv_obj_set_height(ui_Min0, 58);
  lv_obj_set_x(ui_Min0, 29);
  lv_obj_set_y(ui_Min0, -10);
  lv_obj_set_align(ui_Min0, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Min0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Min0, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_Min0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Min0, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_min0label = lv_label_create(ui_Min0);
  lv_obj_set_width(ui_min0label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_min0label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_min0label, LV_ALIGN_CENTER);

  setTimechar(timeset[2], 2);

  ui_object_set_themeable_style_property(ui_min0label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_min0label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Front);
  lv_obj_set_style_text_font(ui_min0label, &ui_font_CLOCKFont2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Min1 = lv_btn_create(ui_SETTIME);
  lv_obj_set_width(ui_Min1, 44);
  lv_obj_set_height(ui_Min1, 58);
  lv_obj_set_x(ui_Min1, 75);
  lv_obj_set_y(ui_Min1, -10);
  lv_obj_set_align(ui_Min1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Min1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Min1, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  ui_object_set_themeable_style_property(ui_Min1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                         _ui_theme_color_Mask2);
  ui_object_set_themeable_style_property(ui_Min1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                         _ui_theme_alpha_Mask2);

  ui_min1label = lv_label_create(ui_Min1);
  lv_obj_set_width(ui_min1label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_min1label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_min1label, LV_ALIGN_CENTER);

  setTimechar(timeset[3], 3);

  ui_object_set_themeable_style_property(ui_min1label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_min1label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Front);
  lv_obj_set_style_text_font(ui_min1label, &ui_font_CLOCKFont2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_settimeLabel1 = lv_label_create(ui_SETTIME);
  lv_obj_set_width(ui_settimeLabel1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_settimeLabel1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_settimeLabel1, 0);
  lv_obj_set_y(ui_settimeLabel1, -70);
  lv_obj_set_align(ui_settimeLabel1, LV_ALIGN_CENTER);
  if (settimemod == 0) lv_label_set_text(ui_settimeLabel1, "时间校准\n------------------\n时                  分");
  else lv_label_set_text(ui_settimeLabel1, "闹钟设定\n------------------\n时                  分");

  ui_object_set_themeable_style_property(ui_settimeLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                         _ui_theme_color_Front);
  ui_object_set_themeable_style_property(ui_settimeLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                         _ui_theme_alpha_Front);

  lv_obj_set_style_text_align(ui_settimeLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_settimeLabel1, &ui_font_SongDenisty16, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_ButtonBACK2, ui_event_ButtonBACK2, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_getTWifiBtn, ui_event_getTWifiBtn, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_timeSetBtn, ui_event_timeSetBtn, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Hour0, ui_event_Hour0, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Hour1, ui_event_Hour1, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Min0, ui_event_Min0, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Min1, ui_event_Min1, LV_EVENT_ALL, NULL);
  lv_group_remove_all_objs(grouphand);

  lv_group_add_obj(grouphand, ui_Hour0);
  lv_group_add_obj(grouphand, ui_Hour1);
  lv_group_add_obj(grouphand, ui_Min0);
  lv_group_add_obj(grouphand, ui_Min1);
  lv_group_add_obj(grouphand, ui_timeSetBtn);
  lv_group_add_obj(grouphand, ui_getTWifiBtn);
  lv_group_add_obj(grouphand, ui_ButtonBACK2);
}
