// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: dht8-3

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Back[2] = {0x181F25, 0xD4E4F6};
const ui_theme_variable_t _ui_theme_alpha_Back[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Front[2] = {0x93C3FD, 0x0E2B64};
const ui_theme_variable_t _ui_theme_alpha_Front[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Mask1[2] = {0xA3B5D5, 0xA1B4DE};
const ui_theme_variable_t _ui_theme_alpha_Mask1[2] = {128, 128};

const ui_theme_variable_t _ui_theme_color_Mask2[2] = {0x062757, 0x6DA2EC};
const ui_theme_variable_t _ui_theme_alpha_Mask2[2] = {200, 225};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

